apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: org2-net-ca-tools
  namespace: org2-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: org2-net-ca-tools
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-prod
        namespace: flux-prod
      chart: platforms/hyperledger-fabric/charts/fabric-catools
  values:
    metadata:
      namespace: org2-net
      name: ca-tools
      component_type: orderer
      org_name: org2
      proxy: none
    replicaCount: 1

    image:
      alpineutils: ghcr.io/hyperledger/bevel-alpine:latest
      catools: ghcr.io/hyperledger/bevel-fabric-ca-tools:1.2.1
      pullPolicy: IfNotPresent
    
    storage:
      storageclassname: org2-bevel-storageclass
      storagesize: 512Mi
    
    vault:
      role: vault-role
      address: http://40.114.165.220:20001
      authpath: prodorg2
      secretusers: secretsv2/data/org2/ordererOrganizations/org2-net/users
      secretorderer: secretsv2/data/org2/ordererOrganizations/org2-net/orderers
      secretpeer: secretsv2/data/org2/ordererOrganizations/org2-net/peers
      secretpeerorderertls: secretsv2/data/org2/ordererOrganizations/org2-net/orderer/tls
      secretcert: secretsv2/data/org2/ordererOrganizations/org2-net/ca?ca.org2-net-cert.pem
      secretkey: secretsv2/data/org2/ordererOrganizations/org2-net/ca?org2-net-CA.key
      secretcouchdb: secretsv2/data/org2/credentials/org2-net/couchdb/org2
      secretconfigfile: secretsv2/data/org2/ordererOrganizations/org2-net/msp/config
      serviceaccountname: vault-auth
      type: hashicorp
      imagesecretname: regcred
    
    healthcheck: 
      retries: 10
      sleepTimeAfterError: 2

    
    org_data:
      external_url_suffix: develop.local.com
      component_subject: O=Org2,OU=Org2,L=51.50/-0.13/London,C=GB
      cert_subject: O=Org2/OU=Org2/L=51.50,-0.13,London/C=GB
      component_country: UK
      component_state: London
      component_location: London
      ca_url: ca.org2-net:7054

    orderers:
      name: orderer1-orderer2-orderer3-
