apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: joinchannel-peer0-join-allchannel-org1-peer0
  namespace: org1-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: joinchannel-peer0-join-allchannel-org1-peer0
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-prod
        namespace: flux-prod
      chart: platforms/hyperledger-fabric/charts/fabric-channel-join
  values:
    metadata:
      namespace: org1-net
      images:
        fabrictools: ghcr.io/hyperledger/bevel-fabric-tools:2.2.2
        alpineutils: ghcr.io/hyperledger/bevel-alpine:latest

    peer:
      name: peer0
      address: peer0.org1-net:7051
      localmspid: org1MSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://40.114.165.220:20001
      authpath: prodorg1
      adminsecretprefix: secretsv2/data/org1/peerOrganizations/org1-net/users/admin
      orderersecretprefix: secretsv2/data/org1/peerOrganizations/org1-net/orderer
      serviceaccountname: vault-auth
      type: hashicorp
      imagesecretname: regcred

    channel:
      name: allchannel      
    orderer:
      address: orderer1.org2-net:7050
