apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: org2-vaultk8s-job
  namespace: org2-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: org2-vaultk8s-job
  interval: 1m
  chart:
   spec:
    chart: platforms/shared/charts/bevel-vault-mgmt
    sourceRef:
      kind: GitRepository
      name: flux-prod
      namespace: flux-prod
  values:
    nameOverride: org2-vaultk8s-job
    global:
      serviceAccountName: vault-auth
      cluster:
        cloudNativeServices: false
        kubernetesUrl: https://hlfabriccluster-dns-5fbhjmlu.hcp.westeurope.azmk8s.io:443
      vault:
        type: hashicorp
        role: vault-role
        address: http://51.124.55.229/:20001
        authPath: prodorg2
        network: fabric
        secretEngine: secretsv2
        secretPrefix: "data/org2"
        tls:
    image:
      repository: ghcr.io/hyperledger/bevel-alpine
      tag: latest
      pullSecret: "regcred"
